# Generated by Django 3.0.5 on 2020-04-01 20:35

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('meta_description', models.CharField(max_length=64)),
                ('ogp_title', models.CharField(max_length=16)),
                ('ogp_img', models.ImageField(upload_to='ogp_img')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contents', markdownx.models.MarkdownxField(help_text='To Put Artile', verbose_name='Contents')),
            ],
        ),
    ]
