# Generated by Django 3.0.5 on 2020-04-09 12:06

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_auto_20200408_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profimg', models.ImageField(upload_to='author/')),
                ('name', models.CharField(max_length=16)),
                ('contents', markdownx.models.MarkdownxField(help_text='To Put your profile', verbose_name='Contents')),
            ],
        ),
    ]
